.libPaths(c("/home/fbartuyurdacan/jmvReport/build/R4.5.0-x64-linux", "/app/lib/jamovi/modules/jmv/R", "/app/lib/R/library"))
suppressMessages(library(jmvReport))
cat("loaded jmvReport", as.character(packageVersion("jmvReport")), "\n")
tg <- ToothGrowth; tg$dose <- factor(tg$dose)
mt <- mtcars; mt$am <- factor(mt$am); mt$vs <- factor(mt$vs)
cat("\n=== aiTtestIS\n"); r <- jmvReport::aiTtestIS(data = tg, vars = "len", group = "supp", welchs = TRUE, mann = TRUE, ci = TRUE, lang = "tr"); print(r$ttest); print(r$desc); cat(strip_html <- gsub("<[^>]+>", "", r$report$content), "\n")
cat("\n=== aiAnovaOneW\n"); r <- jmvReport::aiAnovaOneW(data = tg, deps = "len", group = "dose", welchs = TRUE, kruskal = TRUE, lang = "en"); print(r$anova); print(r$kw); cat(gsub("<[^>]+>", "", r$report$content), "\n"); cat(gsub("<[^>]+>", " ", r$postHoc$content), "\n")
cat("\n=== aiCorr\n"); r <- jmvReport::aiCorr(data = iris, vars = c("Sepal.Length", "Sepal.Width", "Petal.Length"), spearman = TRUE, ci = TRUE, lang = "tr"); print(r$pairs); cat(gsub("<[^>]+>", "", r$report$content), "\n")
cat("\n=== aiContTables\n"); r <- jmvReport::aiContTables(data = mt, rows = "am", cols = "vs", fisher = TRUE, chiSqCorr = TRUE, pcRow = TRUE, lang = "en"); print(r$tests); print(r$nom); cat(gsub("<[^>]+>", " ", r$freqs$content), "\n"); cat(gsub("<[^>]+>", "", r$report$content), "\n")
cat("\n=== reportOmv (installed)\n"); r <- jmvReport::reportOmv(file = "/app/lib/R/library/jmvReadWrite/extdata/ToothGrowth.omv", run = TRUE, useLLM = FALSE, lang = "en", secTables = TRUE); cat(gsub("<[^>]+>", "", r$info$content), "\n"); cat(gsub("<[^>]+>", "", r$method$content), "\n"); print(r$list)
