
# This file is automatically generated, you probably don't want to edit this

aiAnovaOneWOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "aiAnovaOneWOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            deps = NULL,
            group = NULL,
            fishers = TRUE,
            welchs = FALSE,
            kruskal = FALSE,
            phMethod = "tukey",
            desc = TRUE,
            norm = TRUE,
            eqv = TRUE,
            useLLM = FALSE,
            backend = "auto",
            interp = TRUE,
            polish = FALSE,
            model = "qwen3.5:4b",
            endpoint = "", ...) {

            super$initialize(
                package="jmvReport",
                name="aiAnovaOneW",
                requiresData=TRUE,
                ...)

            private$..deps <- jmvcore::OptionVariables$new(
                "deps",
                deps,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..fishers <- jmvcore::OptionBool$new(
                "fishers",
                fishers,
                default=TRUE)
            private$..welchs <- jmvcore::OptionBool$new(
                "welchs",
                welchs,
                default=FALSE)
            private$..kruskal <- jmvcore::OptionBool$new(
                "kruskal",
                kruskal,
                default=FALSE)
            private$..phMethod <- jmvcore::OptionList$new(
                "phMethod",
                phMethod,
                options=list(
                    "none",
                    "tukey",
                    "gamesHowell"),
                default="tukey")
            private$..desc <- jmvcore::OptionBool$new(
                "desc",
                desc,
                default=TRUE)
            private$..norm <- jmvcore::OptionBool$new(
                "norm",
                norm,
                default=TRUE)
            private$..eqv <- jmvcore::OptionBool$new(
                "eqv",
                eqv,
                default=TRUE)
            private$..useLLM <- jmvcore::OptionBool$new(
                "useLLM",
                useLLM,
                default=FALSE)
            private$..backend <- jmvcore::OptionList$new(
                "backend",
                backend,
                options=list(
                    "auto",
                    "ollama",
                    "builtin",
                    "openai_api",
                    "openai"),
                default="auto")
            private$..interp <- jmvcore::OptionBool$new(
                "interp",
                interp,
                default=TRUE)
            private$..polish <- jmvcore::OptionBool$new(
                "polish",
                polish,
                default=FALSE)
            private$..model <- jmvcore::OptionString$new(
                "model",
                model,
                default="qwen3.5:4b")
            private$..endpoint <- jmvcore::OptionString$new(
                "endpoint",
                endpoint,
                default="")

            self$.addOption(private$..deps)
            self$.addOption(private$..group)
            self$.addOption(private$..fishers)
            self$.addOption(private$..welchs)
            self$.addOption(private$..kruskal)
            self$.addOption(private$..phMethod)
            self$.addOption(private$..desc)
            self$.addOption(private$..norm)
            self$.addOption(private$..eqv)
            self$.addOption(private$..useLLM)
            self$.addOption(private$..backend)
            self$.addOption(private$..interp)
            self$.addOption(private$..polish)
            self$.addOption(private$..model)
            self$.addOption(private$..endpoint)
        }),
    active = list(
        deps = function() private$..deps$value,
        group = function() private$..group$value,
        fishers = function() private$..fishers$value,
        welchs = function() private$..welchs$value,
        kruskal = function() private$..kruskal$value,
        phMethod = function() private$..phMethod$value,
        desc = function() private$..desc$value,
        norm = function() private$..norm$value,
        eqv = function() private$..eqv$value,
        useLLM = function() private$..useLLM$value,
        backend = function() private$..backend$value,
        interp = function() private$..interp$value,
        polish = function() private$..polish$value,
        model = function() private$..model$value,
        endpoint = function() private$..endpoint$value),
    private = list(
        ..deps = NA,
        ..group = NA,
        ..fishers = NA,
        ..welchs = NA,
        ..kruskal = NA,
        ..phMethod = NA,
        ..desc = NA,
        ..norm = NA,
        ..eqv = NA,
        ..useLLM = NA,
        ..backend = NA,
        ..interp = NA,
        ..polish = NA,
        ..model = NA,
        ..endpoint = NA)
)

aiAnovaOneWResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "aiAnovaOneWResults",
    inherit = jmvcore::Group,
    active = list(
        anova = function() private$.items[["anova"]],
        kw = function() private$.items[["kw"]],
        desc = function() private$.items[["desc"]],
        norm = function() private$.items[["norm"]],
        eqv = function() private$.items[["eqv"]],
        postHoc = function() private$.items[["postHoc"]],
        report = function() private$.items[["report"]],
        warnings = function() private$.items[["warnings"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="One-Way ANOVA + Report",
                refs=list(
                    "jmvReport",
                    "apa7"))
            self$add(jmvcore::Table$new(
                options=options,
                name="anova",
                title="One-Way ANOVA",
                rows="(deps)",
                clearWith=list(
                    "group",
                    "fishers",
                    "welchs"),
                columns=list(
                    list(
                        `name`="dep",
                        `title`="",
                        `type`="text",
                        `combineBelow`=TRUE),
                    list(
                        `name`="test[fisher]",
                        `title`="",
                        `type`="text",
                        `content`="Fisher's",
                        `visible`="(fishers)"),
                    list(
                        `name`="F[fisher]",
                        `title`="F",
                        `type`="number",
                        `visible`="(fishers)"),
                    list(
                        `name`="df1[fisher]",
                        `title`="df1",
                        `type`="number",
                        `visible`="(fishers)"),
                    list(
                        `name`="df2[fisher]",
                        `title`="df2",
                        `type`="number",
                        `visible`="(fishers)"),
                    list(
                        `name`="p[fisher]",
                        `title`="p",
                        `type`="number",
                        `format`="zto,pvalue",
                        `visible`="(fishers)"),
                    list(
                        `name`="test[welch]",
                        `title`="",
                        `type`="text",
                        `content`="Welch's",
                        `visible`="(welchs)"),
                    list(
                        `name`="F[welch]",
                        `title`="F",
                        `type`="number",
                        `visible`="(welchs)"),
                    list(
                        `name`="df1[welch]",
                        `title`="df1",
                        `type`="number",
                        `visible`="(welchs)"),
                    list(
                        `name`="df2[welch]",
                        `title`="df2",
                        `type`="number",
                        `visible`="(welchs)"),
                    list(
                        `name`="p[welch]",
                        `title`="p",
                        `type`="number",
                        `format`="zto,pvalue",
                        `visible`="(welchs)"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="kw",
                title="Kruskal-Wallis",
                visible="(kruskal)",
                rows="(deps)",
                clearWith=list(
                    "group"),
                columns=list(
                    list(
                        `name`="name",
                        `title`="",
                        `type`="text"),
                    list(
                        `name`="chiSq",
                        `title`="\u03C7\u00B2",
                        `type`="number"),
                    list(
                        `name`="df",
                        `title`="df",
                        `type`="integer"),
                    list(
                        `name`="p",
                        `title`="p",
                        `type`="number",
                        `format`="zto,pvalue"),
                    list(
                        `name`="es",
                        `title`="\u03B5\u00B2",
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="desc",
                title="Group Descriptives",
                visible="(desc)",
                rows=0,
                clearWith=list(
                    "group",
                    "deps"),
                columns=list(
                    list(
                        `name`="dep",
                        `title`="",
                        `type`="text",
                        `combineBelow`=TRUE),
                    list(
                        `name`="group",
                        `title`="Group",
                        `type`="text"),
                    list(
                        `name`="num",
                        `title`="N",
                        `type`="integer"),
                    list(
                        `name`="mean",
                        `title`="Mean",
                        `type`="number"),
                    list(
                        `name`="sd",
                        `title`="SD",
                        `type`="number"),
                    list(
                        `name`="se",
                        `title`="SE",
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="norm",
                title="Normality Test (Shapiro-Wilk)",
                visible="(norm)",
                rows="(deps)",
                clearWith=list(
                    "group"),
                columns=list(
                    list(
                        `name`="name",
                        `title`="",
                        `type`="text"),
                    list(
                        `name`="w",
                        `title`="W",
                        `type`="number"),
                    list(
                        `name`="p",
                        `title`="p",
                        `type`="number",
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="eqv",
                title="Homogeneity of Variances Test (Levene's)",
                visible="(eqv)",
                rows="(deps)",
                clearWith=list(
                    "group"),
                columns=list(
                    list(
                        `name`="dep",
                        `title`="",
                        `type`="text"),
                    list(
                        `name`="F",
                        `title`="F",
                        `type`="number"),
                    list(
                        `name`="df1",
                        `title`="df1",
                        `type`="integer"),
                    list(
                        `name`="df2",
                        `title`="df2",
                        `type`="integer"),
                    list(
                        `name`="p",
                        `title`="p",
                        `type`="number",
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="postHoc",
                title="Post Hoc Comparisons",
                visible="(phMethod:tukey || phMethod:gamesHowell || kruskal)",
                clearWith=list(
                    "group",
                    "deps",
                    "phMethod",
                    "kruskal")))
            self$add(jmvcore::Html$new(
                options=options,
                name="report",
                title="Report text",
                visible=TRUE,
                clearWith=list(
                    "useLLM",
                    "backend",
                    "interp",
                    "polish",
                    "model",
                    "endpoint")))
            self$add(jmvcore::Html$new(
                options=options,
                name="warnings",
                title="Warnings",
                visible=FALSE,
                clearWith=list(
                    "useLLM",
                    "backend",
                    "interp",
                    "polish",
                    "model",
                    "endpoint")))}))

aiAnovaOneWBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "aiAnovaOneWBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jmvReport",
                name = "aiAnovaOneW",
                version = c(1,0,0),
                options = options,
                results = aiAnovaOneWResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' One-Way ANOVA + Report
#'
#' One-way ANOVA (Fisher / Welch) and Kruskal-Wallis with post hoc tests and
#' an APA-style report paragraph.
#' @param data .
#' @param deps .
#' @param group .
#' @param fishers .
#' @param welchs .
#' @param kruskal .
#' @param phMethod .
#' @param desc .
#' @param norm .
#' @param eqv .
#' @param useLLM .
#' @param backend .
#' @param interp .
#' @param polish .
#' @param model .
#' @param endpoint .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$anova} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$kw} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$desc} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$norm} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$eqv} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$postHoc} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$report} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$warnings} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$anova$asDF}
#'
#' \code{as.data.frame(results$anova)}
#'
#' @export
aiAnovaOneW <- function(
    data,
    deps,
    group,
    fishers = TRUE,
    welchs = FALSE,
    kruskal = FALSE,
    phMethod = "tukey",
    desc = TRUE,
    norm = TRUE,
    eqv = TRUE,
    useLLM = FALSE,
    backend = "auto",
    interp = TRUE,
    polish = FALSE,
    model = "qwen3.5:4b",
    endpoint = "") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("aiAnovaOneW requires jmvcore to be installed (restart may be required)")

    if ( ! missing(deps)) deps <- jmvcore::resolveQuo(jmvcore::enquo(deps))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(deps), deps, NULL),
            `if`( ! missing(group), group, NULL))

    for (v in group) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- aiAnovaOneWOptions$new(
        deps = deps,
        group = group,
        fishers = fishers,
        welchs = welchs,
        kruskal = kruskal,
        phMethod = phMethod,
        desc = desc,
        norm = norm,
        eqv = eqv,
        useLLM = useLLM,
        backend = backend,
        interp = interp,
        polish = polish,
        model = model,
        endpoint = endpoint)

    analysis <- aiAnovaOneWClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
