
# This file is automatically generated, you probably don't want to edit this

aiContTablesOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "aiContTablesOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            rows = NULL,
            cols = NULL,
            chiSq = TRUE,
            chiSqCorr = FALSE,
            likeRat = FALSE,
            fisher = FALSE,
            phiCra = TRUE,
            contCoef = FALSE,
            pcRow = FALSE,
            pcCol = FALSE,
            exp = FALSE,
            lang = "tr",
            useLLM = TRUE,
            model = "qwen3.5:4b",
            endpoint = "http://localhost:11434", ...) {

            super$initialize(
                package="jmvReport",
                name="aiContTables",
                requiresData=TRUE,
                ...)

            private$..rows <- jmvcore::OptionVariable$new(
                "rows",
                rows,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..cols <- jmvcore::OptionVariable$new(
                "cols",
                cols,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..chiSq <- jmvcore::OptionBool$new(
                "chiSq",
                chiSq,
                default=TRUE)
            private$..chiSqCorr <- jmvcore::OptionBool$new(
                "chiSqCorr",
                chiSqCorr,
                default=FALSE)
            private$..likeRat <- jmvcore::OptionBool$new(
                "likeRat",
                likeRat,
                default=FALSE)
            private$..fisher <- jmvcore::OptionBool$new(
                "fisher",
                fisher,
                default=FALSE)
            private$..phiCra <- jmvcore::OptionBool$new(
                "phiCra",
                phiCra,
                default=TRUE)
            private$..contCoef <- jmvcore::OptionBool$new(
                "contCoef",
                contCoef,
                default=FALSE)
            private$..pcRow <- jmvcore::OptionBool$new(
                "pcRow",
                pcRow,
                default=FALSE)
            private$..pcCol <- jmvcore::OptionBool$new(
                "pcCol",
                pcCol,
                default=FALSE)
            private$..exp <- jmvcore::OptionBool$new(
                "exp",
                exp,
                default=FALSE)
            private$..lang <- jmvcore::OptionList$new(
                "lang",
                lang,
                options=list(
                    "tr",
                    "en"),
                default="tr")
            private$..useLLM <- jmvcore::OptionBool$new(
                "useLLM",
                useLLM,
                default=TRUE)
            private$..model <- jmvcore::OptionString$new(
                "model",
                model,
                default="qwen3.5:4b")
            private$..endpoint <- jmvcore::OptionString$new(
                "endpoint",
                endpoint,
                default="http://localhost:11434")

            self$.addOption(private$..rows)
            self$.addOption(private$..cols)
            self$.addOption(private$..chiSq)
            self$.addOption(private$..chiSqCorr)
            self$.addOption(private$..likeRat)
            self$.addOption(private$..fisher)
            self$.addOption(private$..phiCra)
            self$.addOption(private$..contCoef)
            self$.addOption(private$..pcRow)
            self$.addOption(private$..pcCol)
            self$.addOption(private$..exp)
            self$.addOption(private$..lang)
            self$.addOption(private$..useLLM)
            self$.addOption(private$..model)
            self$.addOption(private$..endpoint)
        }),
    active = list(
        rows = function() private$..rows$value,
        cols = function() private$..cols$value,
        chiSq = function() private$..chiSq$value,
        chiSqCorr = function() private$..chiSqCorr$value,
        likeRat = function() private$..likeRat$value,
        fisher = function() private$..fisher$value,
        phiCra = function() private$..phiCra$value,
        contCoef = function() private$..contCoef$value,
        pcRow = function() private$..pcRow$value,
        pcCol = function() private$..pcCol$value,
        exp = function() private$..exp$value,
        lang = function() private$..lang$value,
        useLLM = function() private$..useLLM$value,
        model = function() private$..model$value,
        endpoint = function() private$..endpoint$value),
    private = list(
        ..rows = NA,
        ..cols = NA,
        ..chiSq = NA,
        ..chiSqCorr = NA,
        ..likeRat = NA,
        ..fisher = NA,
        ..phiCra = NA,
        ..contCoef = NA,
        ..pcRow = NA,
        ..pcCol = NA,
        ..exp = NA,
        ..lang = NA,
        ..useLLM = NA,
        ..model = NA,
        ..endpoint = NA)
)

aiContTablesResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "aiContTablesResults",
    inherit = jmvcore::Group,
    active = list(
        freqs = function() private$.items[["freqs"]],
        tests = function() private$.items[["tests"]],
        nom = function() private$.items[["nom"]],
        report = function() private$.items[["report"]],
        warnings = function() private$.items[["warnings"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Contingency Tables + Report",
                refs=list(
                    "jmvReport",
                    "apa7"))
            self$add(jmvcore::Html$new(
                options=options,
                name="freqs",
                title="Contingency Table",
                clearWith=list(
                    "rows",
                    "cols",
                    "pcRow",
                    "pcCol",
                    "exp")))
            self$add(jmvcore::Table$new(
                options=options,
                name="tests",
                title="\u03C7\u00B2 Tests",
                rows=0,
                clearWith=list(
                    "rows",
                    "cols",
                    "chiSq",
                    "chiSqCorr",
                    "likeRat",
                    "fisher"),
                columns=list(
                    list(
                        `name`="test", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Value", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="integer"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="nom",
                title="Nominal (effect sizes)",
                rows=1,
                visible="(phiCra || contCoef)",
                clearWith=list(
                    "rows",
                    "cols"),
                columns=list(
                    list(
                        `name`="cont", 
                        `title`="Contingency coefficient", 
                        `type`="number", 
                        `visible`="(contCoef)"),
                    list(
                        `name`="phi", 
                        `title`="Phi", 
                        `type`="number", 
                        `visible`="(phiCra)"),
                    list(
                        `name`="cra", 
                        `title`="Cram\u00E9r's V", 
                        `type`="number", 
                        `visible`="(phiCra)"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="report",
                title="Report text",
                visible=TRUE,
                clearWith=list(
                    "lang",
                    "useLLM",
                    "model",
                    "endpoint")))
            self$add(jmvcore::Html$new(
                options=options,
                name="warnings",
                title="Warnings",
                visible=FALSE,
                clearWith=list(
                    "lang",
                    "useLLM",
                    "model",
                    "endpoint")))}))

aiContTablesBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "aiContTablesBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jmvReport",
                name = "aiContTables",
                version = c(1,0,0),
                options = options,
                results = aiContTablesResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Contingency Tables + Report
#'
#' Chi-square test of independence (with Fisher's exact test and effect sizes) 
#' and an APA-style report paragraph.
#' @param data .
#' @param rows .
#' @param cols .
#' @param chiSq .
#' @param chiSqCorr .
#' @param likeRat .
#' @param fisher .
#' @param phiCra .
#' @param contCoef .
#' @param pcRow .
#' @param pcCol .
#' @param exp .
#' @param lang .
#' @param useLLM .
#' @param model .
#' @param endpoint .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$freqs} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$tests} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$nom} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$report} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$warnings} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$tests$asDF}
#'
#' \code{as.data.frame(results$tests)}
#'
#' @export
aiContTables <- function(
    data,
    rows,
    cols,
    chiSq = TRUE,
    chiSqCorr = FALSE,
    likeRat = FALSE,
    fisher = FALSE,
    phiCra = TRUE,
    contCoef = FALSE,
    pcRow = FALSE,
    pcCol = FALSE,
    exp = FALSE,
    lang = "tr",
    useLLM = TRUE,
    model = "qwen3.5:4b",
    endpoint = "http://localhost:11434") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("aiContTables requires jmvcore to be installed (restart may be required)")

    if ( ! missing(rows)) rows <- jmvcore::resolveQuo(jmvcore::enquo(rows))
    if ( ! missing(cols)) cols <- jmvcore::resolveQuo(jmvcore::enquo(cols))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(rows), rows, NULL),
            `if`( ! missing(cols), cols, NULL))

    for (v in rows) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in cols) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- aiContTablesOptions$new(
        rows = rows,
        cols = cols,
        chiSq = chiSq,
        chiSqCorr = chiSqCorr,
        likeRat = likeRat,
        fisher = fisher,
        phiCra = phiCra,
        contCoef = contCoef,
        pcRow = pcRow,
        pcCol = pcCol,
        exp = exp,
        lang = lang,
        useLLM = useLLM,
        model = model,
        endpoint = endpoint)

    analysis <- aiContTablesClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

