
# This file is automatically generated, you probably don't want to edit this

aiCorrOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "aiCorrOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            pearson = TRUE,
            spearman = FALSE,
            kendall = FALSE,
            ci = FALSE,
            useLLM = FALSE,
            backend = "auto",
            interp = TRUE,
            polish = FALSE,
            model = "qwen3.5:4b",
            endpoint = "", ...) {

            super$initialize(
                package="jmvReport",
                name="aiCorr",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous",
                    "ordinal"),
                permitted=list(
                    "numeric"))
            private$..pearson <- jmvcore::OptionBool$new(
                "pearson",
                pearson,
                default=TRUE)
            private$..spearman <- jmvcore::OptionBool$new(
                "spearman",
                spearman,
                default=FALSE)
            private$..kendall <- jmvcore::OptionBool$new(
                "kendall",
                kendall,
                default=FALSE)
            private$..ci <- jmvcore::OptionBool$new(
                "ci",
                ci,
                default=FALSE)
            private$..useLLM <- jmvcore::OptionBool$new(
                "useLLM",
                useLLM,
                default=FALSE)
            private$..backend <- jmvcore::OptionList$new(
                "backend",
                backend,
                options=list(
                    "auto",
                    "ollama",
                    "builtin",
                    "openai"),
                default="auto")
            private$..interp <- jmvcore::OptionBool$new(
                "interp",
                interp,
                default=TRUE)
            private$..polish <- jmvcore::OptionBool$new(
                "polish",
                polish,
                default=FALSE)
            private$..model <- jmvcore::OptionString$new(
                "model",
                model,
                default="qwen3.5:4b")
            private$..endpoint <- jmvcore::OptionString$new(
                "endpoint",
                endpoint,
                default="")

            self$.addOption(private$..vars)
            self$.addOption(private$..pearson)
            self$.addOption(private$..spearman)
            self$.addOption(private$..kendall)
            self$.addOption(private$..ci)
            self$.addOption(private$..useLLM)
            self$.addOption(private$..backend)
            self$.addOption(private$..interp)
            self$.addOption(private$..polish)
            self$.addOption(private$..model)
            self$.addOption(private$..endpoint)
        }),
    active = list(
        vars = function() private$..vars$value,
        pearson = function() private$..pearson$value,
        spearman = function() private$..spearman$value,
        kendall = function() private$..kendall$value,
        ci = function() private$..ci$value,
        useLLM = function() private$..useLLM$value,
        backend = function() private$..backend$value,
        interp = function() private$..interp$value,
        polish = function() private$..polish$value,
        model = function() private$..model$value,
        endpoint = function() private$..endpoint$value),
    private = list(
        ..vars = NA,
        ..pearson = NA,
        ..spearman = NA,
        ..kendall = NA,
        ..ci = NA,
        ..useLLM = NA,
        ..backend = NA,
        ..interp = NA,
        ..polish = NA,
        ..model = NA,
        ..endpoint = NA)
)

aiCorrResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "aiCorrResults",
    inherit = jmvcore::Group,
    active = list(
        pairs = function() private$.items[["pairs"]],
        report = function() private$.items[["report"]],
        warnings = function() private$.items[["warnings"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Correlation Matrix + Report",
                refs=list(
                    "jmvReport",
                    "apa7"))
            self$add(jmvcore::Table$new(
                options=options,
                name="pairs",
                title="Correlations (pairwise)",
                rows=0,
                clearWith=list(
                    "vars",
                    "pearson",
                    "spearman",
                    "kendall",
                    "ci"),
                columns=list(
                    list(
                        `name`="a", 
                        `title`="Variable 1", 
                        `type`="text"),
                    list(
                        `name`="b", 
                        `title`="Variable 2", 
                        `type`="text"),
                    list(
                        `name`="n", 
                        `title`="N", 
                        `type`="integer"),
                    list(
                        `name`="r", 
                        `title`="Pearson's r", 
                        `type`="number", 
                        `visible`="(pearson)"),
                    list(
                        `name`="rcil", 
                        `title`="Lower", 
                        `type`="number", 
                        `visible`="(pearson && ci)"),
                    list(
                        `name`="rciu", 
                        `title`="Upper", 
                        `type`="number", 
                        `visible`="(pearson && ci)"),
                    list(
                        `name`="rp", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue", 
                        `visible`="(pearson)"),
                    list(
                        `name`="rho", 
                        `title`="Spearman's rho", 
                        `type`="number", 
                        `visible`="(spearman)"),
                    list(
                        `name`="rhop", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue", 
                        `visible`="(spearman)"),
                    list(
                        `name`="tau", 
                        `title`="Kendall's tau-b", 
                        `type`="number", 
                        `visible`="(kendall)"),
                    list(
                        `name`="taup", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue", 
                        `visible`="(kendall)"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="report",
                title="Report text",
                visible=TRUE,
                clearWith=list(
                    "useLLM",
                    "backend",
                    "interp",
                    "polish",
                    "model",
                    "endpoint")))
            self$add(jmvcore::Html$new(
                options=options,
                name="warnings",
                title="Warnings",
                visible=FALSE,
                clearWith=list(
                    "useLLM",
                    "backend",
                    "interp",
                    "polish",
                    "model",
                    "endpoint")))}))

aiCorrBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "aiCorrBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jmvReport",
                name = "aiCorr",
                version = c(1,0,0),
                options = options,
                results = aiCorrResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Correlation Matrix + Report
#'
#' Pearson / Spearman / Kendall correlations with an APA-style report 
#' paragraph.
#' @param data .
#' @param vars .
#' @param pearson .
#' @param spearman .
#' @param kendall .
#' @param ci .
#' @param useLLM .
#' @param backend .
#' @param interp .
#' @param polish .
#' @param model .
#' @param endpoint .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$pairs} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$report} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$warnings} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$pairs$asDF}
#'
#' \code{as.data.frame(results$pairs)}
#'
#' @export
aiCorr <- function(
    data,
    vars,
    pearson = TRUE,
    spearman = FALSE,
    kendall = FALSE,
    ci = FALSE,
    useLLM = FALSE,
    backend = "auto",
    interp = TRUE,
    polish = FALSE,
    model = "qwen3.5:4b",
    endpoint = "") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("aiCorr requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL))


    options <- aiCorrOptions$new(
        vars = vars,
        pearson = pearson,
        spearman = spearman,
        kendall = kendall,
        ci = ci,
        useLLM = useLLM,
        backend = backend,
        interp = interp,
        polish = polish,
        model = model,
        endpoint = endpoint)

    analysis <- aiCorrClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

