
# This file is automatically generated, you probably don't want to edit this

aiTtestISOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "aiTtestISOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            group = NULL,
            students = TRUE,
            welchs = FALSE,
            mann = FALSE,
            effectSize = TRUE,
            ci = FALSE,
            ciWidth = 95,
            desc = TRUE,
            norm = TRUE,
            eqv = TRUE,
            useLLM = FALSE,
            backend = "auto",
            interp = TRUE,
            polish = FALSE,
            model = "qwen3.5:4b",
            endpoint = "", ...) {

            super$initialize(
                package="jmvReport",
                name="aiTtestIS",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..students <- jmvcore::OptionBool$new(
                "students",
                students,
                default=TRUE)
            private$..welchs <- jmvcore::OptionBool$new(
                "welchs",
                welchs,
                default=FALSE)
            private$..mann <- jmvcore::OptionBool$new(
                "mann",
                mann,
                default=FALSE)
            private$..effectSize <- jmvcore::OptionBool$new(
                "effectSize",
                effectSize,
                default=TRUE)
            private$..ci <- jmvcore::OptionBool$new(
                "ci",
                ci,
                default=FALSE)
            private$..ciWidth <- jmvcore::OptionNumber$new(
                "ciWidth",
                ciWidth,
                min=50,
                max=99.9,
                default=95)
            private$..desc <- jmvcore::OptionBool$new(
                "desc",
                desc,
                default=TRUE)
            private$..norm <- jmvcore::OptionBool$new(
                "norm",
                norm,
                default=TRUE)
            private$..eqv <- jmvcore::OptionBool$new(
                "eqv",
                eqv,
                default=TRUE)
            private$..useLLM <- jmvcore::OptionBool$new(
                "useLLM",
                useLLM,
                default=FALSE)
            private$..backend <- jmvcore::OptionList$new(
                "backend",
                backend,
                options=list(
                    "auto",
                    "ollama",
                    "builtin",
                    "openai_api",
                    "openai"),
                default="auto")
            private$..interp <- jmvcore::OptionBool$new(
                "interp",
                interp,
                default=TRUE)
            private$..polish <- jmvcore::OptionBool$new(
                "polish",
                polish,
                default=FALSE)
            private$..model <- jmvcore::OptionString$new(
                "model",
                model,
                default="qwen3.5:4b")
            private$..endpoint <- jmvcore::OptionString$new(
                "endpoint",
                endpoint,
                default="")

            self$.addOption(private$..vars)
            self$.addOption(private$..group)
            self$.addOption(private$..students)
            self$.addOption(private$..welchs)
            self$.addOption(private$..mann)
            self$.addOption(private$..effectSize)
            self$.addOption(private$..ci)
            self$.addOption(private$..ciWidth)
            self$.addOption(private$..desc)
            self$.addOption(private$..norm)
            self$.addOption(private$..eqv)
            self$.addOption(private$..useLLM)
            self$.addOption(private$..backend)
            self$.addOption(private$..interp)
            self$.addOption(private$..polish)
            self$.addOption(private$..model)
            self$.addOption(private$..endpoint)
        }),
    active = list(
        vars = function() private$..vars$value,
        group = function() private$..group$value,
        students = function() private$..students$value,
        welchs = function() private$..welchs$value,
        mann = function() private$..mann$value,
        effectSize = function() private$..effectSize$value,
        ci = function() private$..ci$value,
        ciWidth = function() private$..ciWidth$value,
        desc = function() private$..desc$value,
        norm = function() private$..norm$value,
        eqv = function() private$..eqv$value,
        useLLM = function() private$..useLLM$value,
        backend = function() private$..backend$value,
        interp = function() private$..interp$value,
        polish = function() private$..polish$value,
        model = function() private$..model$value,
        endpoint = function() private$..endpoint$value),
    private = list(
        ..vars = NA,
        ..group = NA,
        ..students = NA,
        ..welchs = NA,
        ..mann = NA,
        ..effectSize = NA,
        ..ci = NA,
        ..ciWidth = NA,
        ..desc = NA,
        ..norm = NA,
        ..eqv = NA,
        ..useLLM = NA,
        ..backend = NA,
        ..interp = NA,
        ..polish = NA,
        ..model = NA,
        ..endpoint = NA)
)

aiTtestISResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "aiTtestISResults",
    inherit = jmvcore::Group,
    active = list(
        ttest = function() private$.items[["ttest"]],
        norm = function() private$.items[["norm"]],
        eqv = function() private$.items[["eqv"]],
        desc = function() private$.items[["desc"]],
        report = function() private$.items[["report"]],
        warnings = function() private$.items[["warnings"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Independent Samples T-Test + Report",
                refs=list(
                    "jmvReport",
                    "apa7"))
            self$add(jmvcore::Table$new(
                options=options,
                name="ttest",
                title="Independent Samples T-Test",
                rows="(vars)",
                clearWith=list(
                    "group",
                    "students",
                    "welchs",
                    "mann",
                    "effectSize",
                    "ci",
                    "ciWidth"),
                columns=list(
                    list(
                        `name`="var[stud]",
                        `title`="",
                        `type`="text",
                        `combineBelow`=TRUE,
                        `visible`="(students)"),
                    list(
                        `name`="name[stud]",
                        `title`="",
                        `type`="text",
                        `content`="Student's t",
                        `visible`="(students)"),
                    list(
                        `name`="stat[stud]",
                        `title`="Statistic",
                        `type`="number",
                        `visible`="(students)"),
                    list(
                        `name`="df[stud]",
                        `title`="df",
                        `type`="number",
                        `visible`="(students)"),
                    list(
                        `name`="p[stud]",
                        `title`="p",
                        `type`="number",
                        `format`="zto,pvalue",
                        `visible`="(students)"),
                    list(
                        `name`="md[stud]",
                        `title`="Mean difference",
                        `type`="number",
                        `visible`="(students)"),
                    list(
                        `name`="cil[stud]",
                        `title`="Lower",
                        `type`="number",
                        `visible`="(students && ci)"),
                    list(
                        `name`="ciu[stud]",
                        `title`="Upper",
                        `type`="number",
                        `visible`="(students && ci)"),
                    list(
                        `name`="es[stud]",
                        `title`="Cohen's d",
                        `type`="number",
                        `visible`="(students && effectSize)"),
                    list(
                        `name`="var[welc]",
                        `title`="",
                        `type`="text",
                        `combineBelow`=TRUE,
                        `visible`="(welchs)"),
                    list(
                        `name`="name[welc]",
                        `title`="",
                        `type`="text",
                        `content`="Welch's t",
                        `visible`="(welchs)"),
                    list(
                        `name`="stat[welc]",
                        `title`="Statistic",
                        `type`="number",
                        `visible`="(welchs)"),
                    list(
                        `name`="df[welc]",
                        `title`="df",
                        `type`="number",
                        `visible`="(welchs)"),
                    list(
                        `name`="p[welc]",
                        `title`="p",
                        `type`="number",
                        `format`="zto,pvalue",
                        `visible`="(welchs)"),
                    list(
                        `name`="md[welc]",
                        `title`="Mean difference",
                        `type`="number",
                        `visible`="(welchs)"),
                    list(
                        `name`="cil[welc]",
                        `title`="Lower",
                        `type`="number",
                        `visible`="(welchs && ci)"),
                    list(
                        `name`="ciu[welc]",
                        `title`="Upper",
                        `type`="number",
                        `visible`="(welchs && ci)"),
                    list(
                        `name`="es[welc]",
                        `title`="Cohen's d",
                        `type`="number",
                        `visible`="(welchs && effectSize)"),
                    list(
                        `name`="var[mann]",
                        `title`="",
                        `type`="text",
                        `combineBelow`=TRUE,
                        `visible`="(mann)"),
                    list(
                        `name`="name[mann]",
                        `title`="",
                        `type`="text",
                        `content`="Mann-Whitney U",
                        `visible`="(mann)"),
                    list(
                        `name`="stat[mann]",
                        `title`="Statistic",
                        `type`="number",
                        `visible`="(mann)"),
                    list(
                        `name`="p[mann]",
                        `title`="p",
                        `type`="number",
                        `format`="zto,pvalue",
                        `visible`="(mann)"),
                    list(
                        `name`="es[mann]",
                        `title`="Rank-biserial r",
                        `type`="number",
                        `visible`="(mann && effectSize)"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="norm",
                title="Normality Test (Shapiro-Wilk)",
                visible="(norm)",
                rows="(vars)",
                clearWith=list(
                    "group"),
                columns=list(
                    list(
                        `name`="name",
                        `title`="",
                        `type`="text"),
                    list(
                        `name`="w",
                        `title`="W",
                        `type`="number"),
                    list(
                        `name`="p",
                        `title`="p",
                        `type`="number",
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="eqv",
                title="Homogeneity of Variances Test (Levene's)",
                visible="(eqv)",
                rows="(vars)",
                clearWith=list(
                    "group"),
                columns=list(
                    list(
                        `name`="name",
                        `title`="",
                        `type`="text"),
                    list(
                        `name`="f",
                        `title`="F",
                        `type`="number"),
                    list(
                        `name`="df",
                        `title`="df",
                        `type`="integer"),
                    list(
                        `name`="df2",
                        `title`="df2",
                        `type`="integer"),
                    list(
                        `name`="p",
                        `title`="p",
                        `type`="number",
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="desc",
                title="Group Descriptives",
                visible="(desc)",
                rows="(vars)",
                clearWith=list(
                    "group"),
                columns=list(
                    list(
                        `name`="dep",
                        `title`="",
                        `type`="text"),
                    list(
                        `name`="group[1]",
                        `title`="Group",
                        `type`="text"),
                    list(
                        `name`="num[1]",
                        `title`="N",
                        `type`="integer"),
                    list(
                        `name`="mean[1]",
                        `title`="Mean",
                        `type`="number"),
                    list(
                        `name`="med[1]",
                        `title`="Median",
                        `type`="number"),
                    list(
                        `name`="sd[1]",
                        `title`="SD",
                        `type`="number"),
                    list(
                        `name`="group[2]",
                        `title`="Group",
                        `type`="text"),
                    list(
                        `name`="num[2]",
                        `title`="N",
                        `type`="integer"),
                    list(
                        `name`="mean[2]",
                        `title`="Mean",
                        `type`="number"),
                    list(
                        `name`="med[2]",
                        `title`="Median",
                        `type`="number"),
                    list(
                        `name`="sd[2]",
                        `title`="SD",
                        `type`="number"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="report",
                title="Report text",
                visible=TRUE,
                clearWith=list(
                    "useLLM",
                    "backend",
                    "interp",
                    "polish",
                    "model",
                    "endpoint")))
            self$add(jmvcore::Html$new(
                options=options,
                name="warnings",
                title="Warnings",
                visible=FALSE,
                clearWith=list(
                    "useLLM",
                    "backend",
                    "interp",
                    "polish",
                    "model",
                    "endpoint")))}))

aiTtestISBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "aiTtestISBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jmvReport",
                name = "aiTtestIS",
                version = c(1,0,0),
                options = options,
                results = aiTtestISResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Independent Samples T-Test + Report
#'
#' Independent samples t-test (Student, Welch, Mann-Whitney) with an APA-style
#' report paragraph.
#' @param data .
#' @param vars .
#' @param group .
#' @param students .
#' @param welchs .
#' @param mann .
#' @param effectSize .
#' @param ci .
#' @param ciWidth .
#' @param desc .
#' @param norm .
#' @param eqv .
#' @param useLLM .
#' @param backend .
#' @param interp .
#' @param polish .
#' @param model .
#' @param endpoint .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$ttest} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$norm} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$eqv} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$desc} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$report} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$warnings} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$ttest$asDF}
#'
#' \code{as.data.frame(results$ttest)}
#'
#' @export
aiTtestIS <- function(
    data,
    vars,
    group,
    students = TRUE,
    welchs = FALSE,
    mann = FALSE,
    effectSize = TRUE,
    ci = FALSE,
    ciWidth = 95,
    desc = TRUE,
    norm = TRUE,
    eqv = TRUE,
    useLLM = FALSE,
    backend = "auto",
    interp = TRUE,
    polish = FALSE,
    model = "qwen3.5:4b",
    endpoint = "") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("aiTtestIS requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(group), group, NULL))

    for (v in group) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- aiTtestISOptions$new(
        vars = vars,
        group = group,
        students = students,
        welchs = welchs,
        mann = mann,
        effectSize = effectSize,
        ci = ci,
        ciWidth = ciWidth,
        desc = desc,
        norm = norm,
        eqv = eqv,
        useLLM = useLLM,
        backend = backend,
        interp = interp,
        polish = polish,
        model = model,
        endpoint = endpoint)

    analysis <- aiTtestISClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
