# ---- Localised strings -------------------------------------------------------

i18n <- function(lang = "tr") {
  lang <- if (identical(lang, "en")) "en" else "tr"
  L <- list(
    tr = list(
      method_title = "Yöntem — İstatistiksel Analiz",
      results_title = "Bulgular",
      info_title = "Bilgi",
      warnings_title = "Uyarılar",
      analysis = "Analiz", variables = "Değişkenler", test = "Test",
      effect = "Etki büyüklüğü", p = "p", n = "N",
      magnitude = c(negligible = "ihmal edilebilir", small = "küçük", medium = "orta", large = "büyük"),
      layer_template = "Metin şablon motoruyla üretildi (yapay zeka kullanılmadı).",
      layer_llm = "Metin şablon motoruyla üretildi ve yerel dil modeli (%s) ile akıcılaştırıldı.",
      llm_unavailable = "Ollama sunucusuna ulaşılamadı (%s); şablon metni gösteriliyor.",
      llm_fidelity_fail = "Dil modeli çıktısı sayı sadakat kontrolünden geçemedi (%s); şablon metni gösteriliyor.",
      file_used = "Dosya", n_analyses = "Analiz sayısı", elapsed = "Süre",
      no_file = "Kaydedilmiş bir jamovi dosyası (.omv) bulunamadı. Lütfen dosyanızı kaydedin ve yolunu 'Dosya' kutusuna yazın ya da boş bırakıp en son kaydedilen dosyanın otomatik bulunmasını sağlayın.",
      unsupported = "Desteklenmeyen analiz (yalnızca tablo listelendi)",
      not_rerun = "Analiz yeniden hesaplanamadı; kaydedilmiş tablolar kullanıldı",
      interp_title = "Yapay Zeka Yorumu",
      interp_note = "Bu bölüm yerel dil modeli (%s) tarafından üretilmiş bir yorumdur; sayılar hesaplanan sonuçlarla doğrulanmıştır, ancak yorumun bilimsel uygunluğu yazarın sorumluluğundadır.",
      software = "Analizler jamovi %s (The jamovi project, 2026) ve R %s (R Core Team, 2026) ile gerçekleştirilmiştir. İstatistiksel anlamlılık düzeyi %s olarak kabul edilmiştir.",
      sec = "s"
    ),
    en = list(
      method_title = "Method — Statistical Analysis",
      results_title = "Results",
      info_title = "Info",
      warnings_title = "Warnings",
      analysis = "Analysis", variables = "Variables", test = "Test",
      effect = "Effect size", p = "p", n = "N",
      magnitude = c(negligible = "negligible", small = "small", medium = "medium", large = "large"),
      layer_template = "Text generated by the template engine (no AI used).",
      layer_llm = "Text generated by the template engine and polished by a local language model (%s).",
      llm_unavailable = "Ollama server could not be reached (%s); showing template text.",
      llm_fidelity_fail = "Language model output failed the number-fidelity check (%s); showing template text.",
      file_used = "File", n_analyses = "Number of analyses", elapsed = "Elapsed",
      no_file = "No saved jamovi file (.omv) was found. Save your file and type its path into the 'File' box, or leave it empty to auto-detect the most recently saved file.",
      unsupported = "Unsupported analysis (tables listed only)",
      not_rerun = "Analysis could not be recomputed; stored tables were used",
      interp_title = "AI Interpretation",
      interp_note = "This section is an interpretation generated by a local language model (%s); numbers were verified against the computed results, but the scientific adequacy of the interpretation remains the author's responsibility.",
      software = "Analyses were performed with jamovi %s (The jamovi project, 2026) and R %s (R Core Team, 2026). Statistical significance was set at %s.",
      sec = "s"
    )
  )
  L[[lang]]
}
