# ---- English interface strings --------------------------------------------

i18n <- function(lang = "en") {
  list(
    method_title = "Method \u2014 Statistical Analysis",
    results_title = "Results",
    info_title = "Info",
    warnings_title = "Warnings",
    analysis = "Analysis", variables = "Variables", test = "Test",
    effect = "Effect size", p = "p", n = "N",
    magnitude = c(negligible = "negligible", small = "small", medium = "medium", large = "large"),
    layer_template = "Text generated by the deterministic template engine (no AI used).",
    layer_llm = "Template text was polished by %s.",
    layer_interp = "Method and Results text came from the deterministic template engine; the interpretation came from %s.",
    llm_unavailable = "No AI backend was available (%s); deterministic template text is shown.",
    llm_fidelity_fail = "AI output failed the number-fidelity check (%s); deterministic template text is shown.",
    file_used = "File", n_analyses = "Number of analyses", elapsed = "Elapsed",
    no_file = "No saved jamovi file (.omv) was found. Save the file and enter its path, or leave the field empty to use the most recently saved .omv file.",
    unsupported = "Unsupported analysis (tables listed only)",
    not_rerun = "Analysis could not be recomputed; stored tables were used",
    interp_title = "AI Interpretation",
    interp_note = "This section was generated by %s. Numbers were checked against the computed results, but the author remains responsible for scientific interpretation.",
    software = "Analyses were performed with jamovi %s (The jamovi project, 2026) and R %s (R Core Team, 2026). Statistical significance was set at %s.",
    sec = "s"
  )
}
