
# This file is automatically generated, you probably don't want to edit this

localAISetupOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "localAISetupOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            install = FALSE,
            repair = FALSE, ...) {

            super$initialize(
                package="jmvReport",
                name="localAISetup",
                requiresData=FALSE,
                ...)

            private$..install <- jmvcore::OptionBool$new(
                "install",
                install,
                default=FALSE)
            private$..repair <- jmvcore::OptionBool$new(
                "repair",
                repair,
                default=FALSE)

            self$.addOption(private$..install)
            self$.addOption(private$..repair)
        }),
    active = list(
        install = function() private$..install$value,
        repair = function() private$..repair$value),
    private = list(
        ..install = NA,
        ..repair = NA)
)

localAISetupResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "localAISetupResults",
    inherit = jmvcore::Group,
    active = list(
        status = function() private$.items[["status"]],
        details = function() private$.items[["details"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Local AI Setup",
                refs=list(
                    "jmvReport"))
            self$add(jmvcore::Html$new(
                options=options,
                name="status",
                title="Status",
                visible=TRUE,
                clearWith=list(
                    "install",
                    "repair")))
            self$add(jmvcore::Html$new(
                options=options,
                name="details",
                title="Installation details",
                visible=TRUE,
                clearWith=list(
                    "install",
                    "repair")))}))

localAISetupBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "localAISetupBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jmvReport",
                name = "localAISetup",
                version = c(1,0,0),
                options = options,
                results = localAISetupResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'na')
        }))

#' Local AI Setup
#'
#' Installs or repairs the optional built-in llama.cpp runtime and the
#' verified 2.39 GB Qwen3.5 model. Nothing is downloaded until the user
#' explicitly starts installation.
#'
#'
#' @examples
#' \donttest{
#' localAISetup()
#'}
#' @param install .
#' @param repair .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$status} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$details} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' @export
localAISetup <- function(
    install = FALSE,
    repair = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("localAISetup requires jmvcore to be installed (restart may be required)")


    options <- localAISetupOptions$new(
        install = install,
        repair = repair)

    analysis <- localAISetupClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
