# ---- Method / Statistical Analysis paragraph --------------------------------

method_sentence <- function(s, lang) {
  o <- s$opts; t <- s$type
  tx2 <- function(tr, en) tx(lang, tr, en)
  switch(t,
    descriptives = tx2("De\u011Fi\u015Fkenler i\u00E7in betimsel istatistikler (ortalama, standart sapma, medyan, minimum-maksimum, frekans ve y\u00FCzde) hesaplanm\u0131\u015Ft\u0131r.",
                       "Descriptive statistics (mean, standard deviation, median, minimum-maximum, frequency and percentage) were computed for the variables."),
    ttestIS = { tests <- c(if (isTRUE(o$students)) tx2("ba\u011F\u0131ms\u0131z \u00F6rneklemler t-testi", "independent samples t-test"), if (isTRUE(o$welchs)) tx2("Welch t-testi", "Welch's t-test"), if (isTRUE(o$mann)) tx2("Mann-Whitney U testi", "Mann-Whitney U test"))
      paste0(tx2(paste0("\u0130ki ba\u011F\u0131ms\u0131z grup aras\u0131ndaki farklar ", join_words(tests, lang), " ile incelenmi\u015Ftir."), paste0("Differences between two independent groups were examined with the ", join_words(tests, lang), ".")),
             if (isTRUE(o$norm)) tx2(" Normallik varsay\u0131m\u0131 Shapiro-Wilk testi ile", " The normality assumption was assessed with the Shapiro-Wilk test") else "", if (isTRUE(o$norm) && isTRUE(o$eqv)) tx2(", varyans homojenli\u011Fi Levene testi ile de\u011Ferlendirilmi\u015Ftir.", " and homogeneity of variances with Levene's test.") else if (isTRUE(o$norm)) "." else if (isTRUE(o$eqv)) tx2(" Varyans homojenli\u011Fi Levene testi ile de\u011Ferlendirilmi\u015Ftir.", " Homogeneity of variances was assessed with Levene's test.") else "",
             if (isTRUE(o$effectSize)) tx2(" Etki b\u00FCy\u00FCkl\u00FC\u011F\u00FC olarak Cohen d (Mann-Whitney i\u00E7in s\u0131ra-\u00E7iftserili korelasyon) raporlanm\u0131\u015Ft\u0131r.", " Cohen's d (rank-biserial correlation for the Mann-Whitney test) was reported as the effect size.") else "") },
    ttestPS = { tests <- c(if (isTRUE(o$students)) tx2("ba\u011F\u0131ml\u0131 \u00F6rneklemler t-testi", "paired samples t-test"), if (isTRUE(o$wilcoxon)) tx2("Wilcoxon i\u015Faretli s\u0131ralar testi", "Wilcoxon signed-rank test"))
      paste0(tx2(paste0("\u0130ki ba\u011F\u0131ml\u0131 \u00F6l\u00E7\u00FCm aras\u0131ndaki farklar ", join_words(tests, lang), " ile incelenmi\u015Ftir."), paste0("Differences between two related measurements were examined with the ", join_words(tests, lang), ".")), if (isTRUE(o$norm)) tx2(" Fark puanlar\u0131n\u0131n normalli\u011Fi Shapiro-Wilk testi ile de\u011Ferlendirilmi\u015Ftir.", " Normality of the difference scores was assessed with the Shapiro-Wilk test.") else "", if (isTRUE(o$effectSize)) tx2(" Etki b\u00FCy\u00FCkl\u00FC\u011F\u00FC olarak Cohen d raporlanm\u0131\u015Ft\u0131r.", " Cohen's d was reported as the effect size.") else "") },
    ttestOneS = tx2("\u00D6rneklem ortalamas\u0131n\u0131n belirlenen test de\u011Ferinden fark\u0131 tek \u00F6rneklem t-testi ile s\u0131nanm\u0131\u015Ft\u0131r.", "The difference between the sample mean and the specified test value was tested with a one-sample t-test."),
    anovaOneW = { tests <- c(if (isTRUE(o$fishers)) tx2("tek y\u00F6nl\u00FC varyans analizi (ANOVA)", "one-way ANOVA"), if (isTRUE(o$welchs)) tx2("Welch ANOVA", "Welch's ANOVA"))
      paste0(tx2(paste0("\u0130kiden fazla ba\u011F\u0131ms\u0131z grup aras\u0131ndaki farklar ", join_words(tests, lang), " ile incelenmi\u015Ftir."), paste0("Differences among more than two independent groups were examined with ", join_words(tests, lang), ".")), if (!identical(o$phMethod, "none")) tx2(paste0(" Anlaml\u0131 farklar i\u00E7in ikili kar\u015F\u0131la\u015Ft\u0131rmalar ", ph_method_name(o$phMethod, lang), " testi ile yap\u0131lm\u0131\u015Ft\u0131r."), paste0(" Post hoc pairwise comparisons were performed with the ", ph_method_name(o$phMethod, lang), " test.")) else "", if (isTRUE(o$norm)) tx2(" Normallik Shapiro-Wilk, varyans homojenli\u011Fi Levene testi ile de\u011Ferlendirilmi\u015Ftir.", " Normality was assessed with the Shapiro-Wilk test and homogeneity of variances with Levene's test.") else "") },
    ANOVA = paste0(tx2(paste0(if (length(s$factors) > 1) paste0(length(s$factors), " fakt\u00F6rl\u00FC ") else "Tek y\u00F6nl\u00FC ", "varyans analizi (ANOVA) ile ", join_words(vapply(s$factors, vn, character(1)), lang), " fakt\u00F6rlerinin ", vn(s$dep), " \u00FCzerindeki temel ve etkile\u015Fim etkileri incelenmi\u015Ftir."), paste0("A ", if (length(s$factors) > 1) paste0(length(s$factors), "-way ") else "one-way ", "ANOVA was used to examine the main and interaction effects of ", join_words(vapply(s$factors, vn, character(1)), lang), " on ", vn(s$dep), ".")),
                   if (length(o$effectSize)) tx2(paste0(" Etki b\u00FCy\u00FCkl\u00FC\u011F\u00FC olarak ", join_words(vapply(o$effectSize, function(e) switch(e, eta = "\u03B7\u00B2", partEta = "k\u0131smi \u03B7\u00B2", omega = "\u03C9\u00B2", e), character(1)), lang), " raporlanm\u0131\u015Ft\u0131r."), paste0(" ", join_words(vapply(o$effectSize, function(e) switch(e, eta = "\u03B7\u00B2", partEta = "partial \u03B7\u00B2", omega = "\u03C9\u00B2", e), character(1)), lang), " was reported as the effect size.")) else "",
                   if (length(s$posthoc)) tx2(paste0(" \u0130kili kar\u015F\u0131la\u015Ft\u0131rmalarda ", ph_method_name(if (length(o$postHocCorr)) o$postHocCorr[1] else "tukey", lang), " d\u00FCzeltmesi kullan\u0131lm\u0131\u015Ft\u0131r."), paste0(" Pairwise comparisons used the ", ph_method_name(if (length(o$postHocCorr)) o$postHocCorr[1] else "tukey", lang), " correction.")) else "",
                   if (isTRUE(o$homo) || isTRUE(o$norm)) tx2(" Varsay\u0131mlar Levene (varyans homojenli\u011Fi) ve Shapiro-Wilk (art\u0131klar\u0131n normalli\u011Fi) testleri ile kontrol edilmi\u015Ftir.", " Assumptions were checked with Levene's test (homogeneity of variances) and the Shapiro-Wilk test (normality of residuals).") else ""),
    ancova = tx2(paste0("Kovaryans analizi (ANCOVA) ile ", join_words(vapply(s$covs, vn, character(1)), lang), " kontrol edildikten sonra ", join_words(vapply(s$factors, vn, character(1)), lang), " fakt\u00F6r\u00FCn\u00FCn ", vn(s$dep), " \u00FCzerindeki etkisi incelenmi\u015Ftir."), paste0("Analysis of covariance (ANCOVA) was used to examine the effect of ", join_words(vapply(s$factors, vn, character(1)), lang), " on ", vn(s$dep), " after controlling for ", join_words(vapply(s$covs, vn, character(1)), lang), ".")),
    anovaRM = paste0(tx2("Tekrarl\u0131 \u00F6l\u00E7\u00FCmler aras\u0131ndaki farklar tekrarl\u0131 \u00F6l\u00E7\u00FCmler varyans analizi ile incelenmi\u015Ftir. K\u00FCresellik varsay\u0131m\u0131 Mauchly testi ile de\u011Ferlendirilmi\u015F", "Differences across repeated measurements were examined with repeated measures ANOVA. Sphericity was assessed with Mauchly's test"), if (any(c("GG", "HF") %in% o$spherCorr)) tx2(paste0(", ihlal durumunda ", join_words(c(if ("GG" %in% o$spherCorr) "Greenhouse-Geisser", if ("HF" %in% o$spherCorr) "Huynh-Feldt"), lang), " d\u00FCzeltmesi uygulanm\u0131\u015Ft\u0131r."), paste0(", and the ", join_words(c(if ("GG" %in% o$spherCorr) "Greenhouse-Geisser", if ("HF" %in% o$spherCorr) "Huynh-Feldt"), lang), " correction was applied when it was violated.")) else "."),
    anovaNP = paste0(tx2("Normal da\u011F\u0131l\u0131m g\u00F6stermeyen de\u011Fi\u015Fkenlerde ikiden fazla ba\u011F\u0131ms\u0131z grup Kruskal-Wallis H testi ile kar\u015F\u0131la\u015Ft\u0131r\u0131lm\u0131\u015Ft\u0131r.", "For non-normally distributed variables, more than two independent groups were compared with the Kruskal-Wallis H test."), if (isTRUE(o$pairsDunn)) tx2(" \u0130kili kar\u015F\u0131la\u015Ft\u0131rmalar Dunn testi (Bonferroni d\u00FCzeltmeli) ile yap\u0131lm\u0131\u015Ft\u0131r.", " Pairwise comparisons were performed with Dunn's test (Bonferroni-adjusted).") else if (isTRUE(o$pairs)) tx2(" \u0130kili kar\u015F\u0131la\u015Ft\u0131rmalar Dwass-Steel-Critchlow-Fligner testi ile yap\u0131lm\u0131\u015Ft\u0131r.", " Pairwise comparisons were performed with the Dwass-Steel-Critchlow-Fligner test.") else "", if (isTRUE(o$es)) tx2(" Etki b\u00FCy\u00FCkl\u00FC\u011F\u00FC olarak \u03B5\u00B2 raporlanm\u0131\u015Ft\u0131r.", " \u03B5\u00B2 was reported as the effect size.") else ""),
    anovaRMNP = paste0(tx2("Normal da\u011F\u0131l\u0131m g\u00F6stermeyen tekrarl\u0131 \u00F6l\u00E7\u00FCmler Friedman testi ile kar\u015F\u0131la\u015Ft\u0131r\u0131lm\u0131\u015Ft\u0131r.", "Non-normally distributed repeated measurements were compared with the Friedman test."), if (isTRUE(o$pairs)) tx2(" \u0130kili kar\u015F\u0131la\u015Ft\u0131rmalar Durbin-Conover testi ile yap\u0131lm\u0131\u015Ft\u0131r.", " Pairwise comparisons were performed with the Durbin-Conover test.") else ""),
    corrMatrix = tx2(paste0("S\u00FCrekli de\u011Fi\u015Fkenler aras\u0131ndaki ili\u015Fkiler ", join_words(c(if (isTRUE(o$pearson)) "Pearson", if (isTRUE(o$spearman)) "Spearman", if (isTRUE(o$kendall)) "Kendall tau-b"), lang), " korelasyon katsay\u0131s\u0131 ile incelenmi\u015Ftir."), paste0("Associations between continuous variables were examined with ", join_words(c(if (isTRUE(o$pearson)) "Pearson's", if (isTRUE(o$spearman)) "Spearman's", if (isTRUE(o$kendall)) "Kendall's tau-b"), lang), " correlation coefficient.")),
    linReg = paste0(tx2(paste0(vn(s$dep), " de\u011Fi\u015Fkenini yordayan etkenler ", if (o$nBlocks > 1) "hiyerar\u015Fik " else "", "\u00E7oklu do\u011Frusal regresyon analizi ile incelenmi\u015Ftir."), paste0("Predictors of ", vn(s$dep), " were examined with ", if (o$nBlocks > 1) "hierarchical " else "", "multiple linear regression.")), if (isTRUE(o$collin)) tx2(" \u00C7oklu ba\u011Flant\u0131 VIF de\u011Ferleri ile", " Multicollinearity was assessed with VIF values") else "", if (isTRUE(o$collin) && isTRUE(o$durbin)) tx2(", art\u0131klar\u0131n ba\u011F\u0131ms\u0131zl\u0131\u011F\u0131 Durbin-Watson testi ile de\u011Ferlendirilmi\u015Ftir.", " and independence of residuals with the Durbin-Watson test.") else if (isTRUE(o$collin)) tx2(" de\u011Ferlendirilmi\u015Ftir.", ".") else if (isTRUE(o$durbin)) tx2(" Art\u0131klar\u0131n ba\u011F\u0131ms\u0131zl\u0131\u011F\u0131 Durbin-Watson testi ile de\u011Ferlendirilmi\u015Ftir.", " Independence of residuals was assessed with the Durbin-Watson test.") else "", if (isTRUE(o$stdEst)) tx2(" Standardize katsay\u0131lar (\u03B2) raporlanm\u0131\u015Ft\u0131r.", " Standardised coefficients (\u03B2) were reported.") else ""),
    logRegBin = paste0(tx2(paste0("\u0130kili sonu\u00E7 de\u011Fi\u015Fkeni ", vn(s$dep), " i\u00E7in yorday\u0131c\u0131lar ikili lojistik regresyon analizi ile incelenmi\u015Ftir."), paste0("Predictors of the binary outcome ", vn(s$dep), " were examined with binomial logistic regression.")), if (isTRUE(o$OR)) tx2(" Odds oranlar\u0131 (OR)", " Odds ratios (OR)") else "", if (isTRUE(o$OR) && isTRUE(o$ciOR)) tx2(" ve %95 g\u00FCven aral\u0131klar\u0131 raporlanm\u0131\u015Ft\u0131r.", " with 95% confidence intervals were reported.") else if (isTRUE(o$OR)) tx2(" raporlanm\u0131\u015Ft\u0131r.", " were reported.") else ""),
    logRegOrd = tx2(paste0("S\u0131ral\u0131 sonu\u00E7 de\u011Fi\u015Fkeni ", vn(s$dep), " i\u00E7in yorday\u0131c\u0131lar ordinal lojistik regresyon ile incelenmi\u015Ftir."), paste0("Predictors of the ordinal outcome ", vn(s$dep), " were examined with ordinal logistic regression.")),
    logRegMulti = tx2(paste0("\u00C7ok kategorili sonu\u00E7 de\u011Fi\u015Fkeni ", vn(s$dep), " i\u00E7in yorday\u0131c\u0131lar multinomial lojistik regresyon ile incelenmi\u015Ftir."), paste0("Predictors of the multinomial outcome ", vn(s$dep), " were examined with multinomial logistic regression.")),
    contTables = paste0(tx2("Kategorik de\u011Fi\u015Fkenler aras\u0131ndaki ili\u015Fkiler ki-kare ba\u011F\u0131ms\u0131zl\u0131k testi ile incelenmi\u015Ftir", "Associations between categorical variables were examined with the chi-square test of independence"), if (isTRUE(o$fisher)) tx2("; beklenen de\u011Ferlerin k\u00FC\u00E7\u00FCk oldu\u011Fu durumlarda Fisher kesin testi kullan\u0131lm\u0131\u015Ft\u0131r", "; Fisher's exact test was used when expected counts were small") else "", if (isTRUE(o$phiCra)) tx2(". Etki b\u00FCy\u00FCkl\u00FC\u011F\u00FC olarak \u03C6 / Cram\u00E9r V raporlanm\u0131\u015Ft\u0131r.", ". \u03C6 / Cram\u00E9r's V was reported as the effect size.") else "."),
    contTablesPaired = tx2("Ba\u011F\u0131ml\u0131 kategorik \u00F6l\u00E7\u00FCmler aras\u0131ndaki de\u011Fi\u015Fim McNemar testi ile incelenmi\u015Ftir.", "Change between related categorical measurements was examined with McNemar's test."),
    propTest2 = tx2("Oranlar binom testi ile belirlenen test de\u011Ferine kar\u015F\u0131 s\u0131nanm\u0131\u015Ft\u0131r.", "Proportions were tested against the specified value with a binomial test."),
    propTestN = tx2("Kategori da\u011F\u0131l\u0131mlar\u0131 ki-kare uyum iyili\u011Fi testi ile s\u0131nanm\u0131\u015Ft\u0131r.", "Category distributions were tested with the chi-square goodness-of-fit test."),
    reliability = tx2(paste0("\u00D6l\u00E7eklerin i\u00E7 tutarl\u0131l\u0131\u011F\u0131 ", join_words(c(if (isTRUE(o$alphaScale)) "Cronbach \u03B1", if (isTRUE(o$omegaScale)) "McDonald \u03C9"), lang), " katsay\u0131s\u0131 ile de\u011Ferlendirilmi\u015Ftir."), paste0("Internal consistency of the scales was evaluated with ", join_words(c(if (isTRUE(o$alphaScale)) "Cronbach's \u03B1", if (isTRUE(o$omegaScale)) "McDonald's \u03C9"), lang), ".")),
    efa = paste0(tx2(paste0("\u00D6l\u00E7e\u011Fin fakt\u00F6r yap\u0131s\u0131 a\u00E7\u0131mlay\u0131c\u0131 fakt\u00F6r analizi ile incelenmi\u015Ftir (\u00E7\u0131kar\u0131m: ", vn(s$extraction), "; d\u00F6nd\u00FCrme: ", vn(s$rotation), "; fakt\u00F6r say\u0131s\u0131: ", vn(s$nFactorMethod), ")."), paste0("The factor structure was examined with exploratory factor analysis (extraction: ", vn(s$extraction), "; rotation: ", vn(s$rotation), "; number of factors: ", vn(s$nFactorMethod), ").")), if (isTRUE(o$kmo) || isTRUE(o$bartlett)) tx2(" \u00D6rneklem yeterlili\u011Fi KMO \u00F6l\u00E7\u00FCt\u00FC ve Bartlett k\u00FCresellik testi ile de\u011Ferlendirilmi\u015Ftir.", " Sampling adequacy was assessed with the KMO measure and Bartlett's test of sphericity.") else ""),
    pca = tx2(paste0("Temel bile\u015Fenler analizi uygulanm\u0131\u015Ft\u0131r (d\u00F6nd\u00FCrme: ", vn(s$rotation), ")."), paste0("Principal component analysis was performed (rotation: ", vn(s$rotation), ").")),
    cfa = tx2("\u00D6l\u00E7\u00FCm modeli do\u011Frulay\u0131c\u0131 fakt\u00F6r analizi ile s\u0131nanm\u0131\u015F; uyum \u03C7\u00B2, CFI, TLI, RMSEA ve SRMR ile de\u011Ferlendirilmi\u015Ftir.", "The measurement model was tested with confirmatory factor analysis; fit was evaluated with \u03C7\u00B2, CFI, TLI, RMSEA and SRMR."),
    mancova = tx2("Birden fazla ba\u011F\u0131ml\u0131 de\u011Fi\u015Fken \u00FCzerindeki grup etkileri \u00E7ok de\u011Fi\u015Fkenli varyans/kovaryans analizi (MANOVA/MANCOVA) ile incelenmi\u015Ftir.", "Group effects on multiple dependent variables were examined with multivariate analysis of variance/covariance (MANOVA/MANCOVA)."),
    tx2(paste0(vn(s$title), " analizi uygulanm\u0131\u015Ft\u0131r."), paste0(vn(s$title), " analysis was performed."))
  )
}

#' Render the Method paragraph for a list of summaries
#' @param summaries A list of summarised analysis objects.
#' @param lang Retained for compatibility; output is always English.
#' @param alpha Statistical significance threshold.
#' @param jamovi_version Optional jamovi version string.
#' @param r_version Optional R version string.
#' @export
render_method_text <- function(summaries, lang = "en", alpha = .05, jamovi_version = NULL, r_version = NULL) {
  lang <- "en"
  L <- i18n(lang)
  types <- character(); sentences <- character()
  for (s in summaries) {
    key <- s$type
    if (key %in% types) next
    types <- c(types, key)
    sentences <- c(sentences, method_sentence(s, lang))
  }
  jv <- if (is.null(jamovi_version)) "2.7" else jamovi_version
  rv <- if (is.null(r_version)) paste(R.version$major, R.version$minor, sep = ".") else r_version
  alpha_txt <- if (lang == "tr") paste0(sym("p"), " &lt; ", sub("^0", "", formatC(alpha, format = "f", digits = 2))) else paste0(sym("p"), " &lt; ", sub("^0", "", formatC(alpha, format = "f", digits = 2)))
  software <- sprintf(L$software, jv, rv, alpha_txt)
  para(paste(c(sentences, software), collapse = " "))
}
