# ---- Method / Statistical Analysis paragraph --------------------------------

method_sentence <- function(s, lang) {
  o <- s$opts; t <- s$type
  tx2 <- function(tr, en) tx(lang, tr, en)
  switch(t,
    descriptives = tx2("Değişkenler için betimsel istatistikler (ortalama, standart sapma, medyan, minimum-maksimum, frekans ve yüzde) hesaplanmıştır.",
                       "Descriptive statistics (mean, standard deviation, median, minimum-maximum, frequency and percentage) were computed for the variables."),
    ttestIS = { tests <- c(if (isTRUE(o$students)) tx2("bağımsız örneklemler t-testi", "independent samples t-test"), if (isTRUE(o$welchs)) tx2("Welch t-testi", "Welch's t-test"), if (isTRUE(o$mann)) tx2("Mann-Whitney U testi", "Mann-Whitney U test"))
      paste0(tx2(paste0("İki bağımsız grup arasındaki farklar ", join_words(tests, lang), " ile incelenmiştir."), paste0("Differences between two independent groups were examined with the ", join_words(tests, lang), ".")),
             if (isTRUE(o$norm)) tx2(" Normallik varsayımı Shapiro-Wilk testi ile", " The normality assumption was assessed with the Shapiro-Wilk test") else "", if (isTRUE(o$norm) && isTRUE(o$eqv)) tx2(", varyans homojenliği Levene testi ile değerlendirilmiştir.", " and homogeneity of variances with Levene's test.") else if (isTRUE(o$norm)) "." else if (isTRUE(o$eqv)) tx2(" Varyans homojenliği Levene testi ile değerlendirilmiştir.", " Homogeneity of variances was assessed with Levene's test.") else "",
             if (isTRUE(o$effectSize)) tx2(" Etki büyüklüğü olarak Cohen d (Mann-Whitney için sıra-çiftserili korelasyon) raporlanmıştır.", " Cohen's d (rank-biserial correlation for the Mann-Whitney test) was reported as the effect size.") else "") },
    ttestPS = { tests <- c(if (isTRUE(o$students)) tx2("bağımlı örneklemler t-testi", "paired samples t-test"), if (isTRUE(o$wilcoxon)) tx2("Wilcoxon işaretli sıralar testi", "Wilcoxon signed-rank test"))
      paste0(tx2(paste0("İki bağımlı ölçüm arasındaki farklar ", join_words(tests, lang), " ile incelenmiştir."), paste0("Differences between two related measurements were examined with the ", join_words(tests, lang), ".")), if (isTRUE(o$norm)) tx2(" Fark puanlarının normalliği Shapiro-Wilk testi ile değerlendirilmiştir.", " Normality of the difference scores was assessed with the Shapiro-Wilk test.") else "", if (isTRUE(o$effectSize)) tx2(" Etki büyüklüğü olarak Cohen d raporlanmıştır.", " Cohen's d was reported as the effect size.") else "") },
    ttestOneS = tx2("Örneklem ortalamasının belirlenen test değerinden farkı tek örneklem t-testi ile sınanmıştır.", "The difference between the sample mean and the specified test value was tested with a one-sample t-test."),
    anovaOneW = { tests <- c(if (isTRUE(o$fishers)) tx2("tek yönlü varyans analizi (ANOVA)", "one-way ANOVA"), if (isTRUE(o$welchs)) tx2("Welch ANOVA", "Welch's ANOVA"))
      paste0(tx2(paste0("İkiden fazla bağımsız grup arasındaki farklar ", join_words(tests, lang), " ile incelenmiştir."), paste0("Differences among more than two independent groups were examined with ", join_words(tests, lang), ".")), if (!identical(o$phMethod, "none")) tx2(paste0(" Anlamlı farklar için ikili karşılaştırmalar ", ph_method_name(o$phMethod, lang), " testi ile yapılmıştır."), paste0(" Post hoc pairwise comparisons were performed with the ", ph_method_name(o$phMethod, lang), " test.")) else "", if (isTRUE(o$norm)) tx2(" Normallik Shapiro-Wilk, varyans homojenliği Levene testi ile değerlendirilmiştir.", " Normality was assessed with the Shapiro-Wilk test and homogeneity of variances with Levene's test.") else "") },
    ANOVA = paste0(tx2(paste0(if (length(s$factors) > 1) paste0(length(s$factors), " faktörlü ") else "Tek yönlü ", "varyans analizi (ANOVA) ile ", join_words(vapply(s$factors, vn, character(1)), lang), " faktörlerinin ", vn(s$dep), " üzerindeki temel ve etkileşim etkileri incelenmiştir."), paste0("A ", if (length(s$factors) > 1) paste0(length(s$factors), "-way ") else "one-way ", "ANOVA was used to examine the main and interaction effects of ", join_words(vapply(s$factors, vn, character(1)), lang), " on ", vn(s$dep), ".")),
                   if (length(o$effectSize)) tx2(paste0(" Etki büyüklüğü olarak ", join_words(vapply(o$effectSize, function(e) switch(e, eta = "η²", partEta = "kısmi η²", omega = "ω²", e), character(1)), lang), " raporlanmıştır."), paste0(" ", join_words(vapply(o$effectSize, function(e) switch(e, eta = "η²", partEta = "partial η²", omega = "ω²", e), character(1)), lang), " was reported as the effect size.")) else "",
                   if (length(s$posthoc)) tx2(paste0(" İkili karşılaştırmalarda ", ph_method_name(if (length(o$postHocCorr)) o$postHocCorr[1] else "tukey", lang), " düzeltmesi kullanılmıştır."), paste0(" Pairwise comparisons used the ", ph_method_name(if (length(o$postHocCorr)) o$postHocCorr[1] else "tukey", lang), " correction.")) else "",
                   if (isTRUE(o$homo) || isTRUE(o$norm)) tx2(" Varsayımlar Levene (varyans homojenliği) ve Shapiro-Wilk (artıkların normalliği) testleri ile kontrol edilmiştir.", " Assumptions were checked with Levene's test (homogeneity of variances) and the Shapiro-Wilk test (normality of residuals).") else ""),
    ancova = tx2(paste0("Kovaryans analizi (ANCOVA) ile ", join_words(vapply(s$covs, vn, character(1)), lang), " kontrol edildikten sonra ", join_words(vapply(s$factors, vn, character(1)), lang), " faktörünün ", vn(s$dep), " üzerindeki etkisi incelenmiştir."), paste0("Analysis of covariance (ANCOVA) was used to examine the effect of ", join_words(vapply(s$factors, vn, character(1)), lang), " on ", vn(s$dep), " after controlling for ", join_words(vapply(s$covs, vn, character(1)), lang), ".")),
    anovaRM = paste0(tx2("Tekrarlı ölçümler arasındaki farklar tekrarlı ölçümler varyans analizi ile incelenmiştir. Küresellik varsayımı Mauchly testi ile değerlendirilmiş", "Differences across repeated measurements were examined with repeated measures ANOVA. Sphericity was assessed with Mauchly's test"), if (any(c("GG", "HF") %in% o$spherCorr)) tx2(paste0(", ihlal durumunda ", join_words(c(if ("GG" %in% o$spherCorr) "Greenhouse-Geisser", if ("HF" %in% o$spherCorr) "Huynh-Feldt"), lang), " düzeltmesi uygulanmıştır."), paste0(", and the ", join_words(c(if ("GG" %in% o$spherCorr) "Greenhouse-Geisser", if ("HF" %in% o$spherCorr) "Huynh-Feldt"), lang), " correction was applied when it was violated.")) else "."),
    anovaNP = paste0(tx2("Normal dağılım göstermeyen değişkenlerde ikiden fazla bağımsız grup Kruskal-Wallis H testi ile karşılaştırılmıştır.", "For non-normally distributed variables, more than two independent groups were compared with the Kruskal-Wallis H test."), if (isTRUE(o$pairsDunn)) tx2(" İkili karşılaştırmalar Dunn testi (Bonferroni düzeltmeli) ile yapılmıştır.", " Pairwise comparisons were performed with Dunn's test (Bonferroni-adjusted).") else if (isTRUE(o$pairs)) tx2(" İkili karşılaştırmalar Dwass-Steel-Critchlow-Fligner testi ile yapılmıştır.", " Pairwise comparisons were performed with the Dwass-Steel-Critchlow-Fligner test.") else "", if (isTRUE(o$es)) tx2(" Etki büyüklüğü olarak ε² raporlanmıştır.", " ε² was reported as the effect size.") else ""),
    anovaRMNP = paste0(tx2("Normal dağılım göstermeyen tekrarlı ölçümler Friedman testi ile karşılaştırılmıştır.", "Non-normally distributed repeated measurements were compared with the Friedman test."), if (isTRUE(o$pairs)) tx2(" İkili karşılaştırmalar Durbin-Conover testi ile yapılmıştır.", " Pairwise comparisons were performed with the Durbin-Conover test.") else ""),
    corrMatrix = tx2(paste0("Sürekli değişkenler arasındaki ilişkiler ", join_words(c(if (isTRUE(o$pearson)) "Pearson", if (isTRUE(o$spearman)) "Spearman", if (isTRUE(o$kendall)) "Kendall tau-b"), lang), " korelasyon katsayısı ile incelenmiştir."), paste0("Associations between continuous variables were examined with ", join_words(c(if (isTRUE(o$pearson)) "Pearson's", if (isTRUE(o$spearman)) "Spearman's", if (isTRUE(o$kendall)) "Kendall's tau-b"), lang), " correlation coefficient.")),
    linReg = paste0(tx2(paste0(vn(s$dep), " değişkenini yordayan etkenler ", if (o$nBlocks > 1) "hiyerarşik " else "", "çoklu doğrusal regresyon analizi ile incelenmiştir."), paste0("Predictors of ", vn(s$dep), " were examined with ", if (o$nBlocks > 1) "hierarchical " else "", "multiple linear regression.")), if (isTRUE(o$collin)) tx2(" Çoklu bağlantı VIF değerleri ile", " Multicollinearity was assessed with VIF values") else "", if (isTRUE(o$collin) && isTRUE(o$durbin)) tx2(", artıkların bağımsızlığı Durbin-Watson testi ile değerlendirilmiştir.", " and independence of residuals with the Durbin-Watson test.") else if (isTRUE(o$collin)) tx2(" değerlendirilmiştir.", ".") else if (isTRUE(o$durbin)) tx2(" Artıkların bağımsızlığı Durbin-Watson testi ile değerlendirilmiştir.", " Independence of residuals was assessed with the Durbin-Watson test.") else "", if (isTRUE(o$stdEst)) tx2(" Standardize katsayılar (β) raporlanmıştır.", " Standardised coefficients (β) were reported.") else ""),
    logRegBin = paste0(tx2(paste0("İkili sonuç değişkeni ", vn(s$dep), " için yordayıcılar ikili lojistik regresyon analizi ile incelenmiştir."), paste0("Predictors of the binary outcome ", vn(s$dep), " were examined with binomial logistic regression.")), if (isTRUE(o$OR)) tx2(" Odds oranları (OR)", " Odds ratios (OR)") else "", if (isTRUE(o$OR) && isTRUE(o$ciOR)) tx2(" ve %95 güven aralıkları raporlanmıştır.", " with 95% confidence intervals were reported.") else if (isTRUE(o$OR)) tx2(" raporlanmıştır.", " were reported.") else ""),
    logRegOrd = tx2(paste0("Sıralı sonuç değişkeni ", vn(s$dep), " için yordayıcılar ordinal lojistik regresyon ile incelenmiştir."), paste0("Predictors of the ordinal outcome ", vn(s$dep), " were examined with ordinal logistic regression.")),
    logRegMulti = tx2(paste0("Çok kategorili sonuç değişkeni ", vn(s$dep), " için yordayıcılar multinomial lojistik regresyon ile incelenmiştir."), paste0("Predictors of the multinomial outcome ", vn(s$dep), " were examined with multinomial logistic regression.")),
    contTables = paste0(tx2("Kategorik değişkenler arasındaki ilişkiler ki-kare bağımsızlık testi ile incelenmiştir", "Associations between categorical variables were examined with the chi-square test of independence"), if (isTRUE(o$fisher)) tx2("; beklenen değerlerin küçük olduğu durumlarda Fisher kesin testi kullanılmıştır", "; Fisher's exact test was used when expected counts were small") else "", if (isTRUE(o$phiCra)) tx2(". Etki büyüklüğü olarak φ / Cramér V raporlanmıştır.", ". φ / Cramér's V was reported as the effect size.") else "."),
    contTablesPaired = tx2("Bağımlı kategorik ölçümler arasındaki değişim McNemar testi ile incelenmiştir.", "Change between related categorical measurements was examined with McNemar's test."),
    propTest2 = tx2("Oranlar binom testi ile belirlenen test değerine karşı sınanmıştır.", "Proportions were tested against the specified value with a binomial test."),
    propTestN = tx2("Kategori dağılımları ki-kare uyum iyiliği testi ile sınanmıştır.", "Category distributions were tested with the chi-square goodness-of-fit test."),
    reliability = tx2(paste0("Ölçeklerin iç tutarlılığı ", join_words(c(if (isTRUE(o$alphaScale)) "Cronbach α", if (isTRUE(o$omegaScale)) "McDonald ω"), lang), " katsayısı ile değerlendirilmiştir."), paste0("Internal consistency of the scales was evaluated with ", join_words(c(if (isTRUE(o$alphaScale)) "Cronbach's α", if (isTRUE(o$omegaScale)) "McDonald's ω"), lang), ".")),
    efa = paste0(tx2(paste0("Ölçeğin faktör yapısı açımlayıcı faktör analizi ile incelenmiştir (çıkarım: ", vn(s$extraction), "; döndürme: ", vn(s$rotation), "; faktör sayısı: ", vn(s$nFactorMethod), ")."), paste0("The factor structure was examined with exploratory factor analysis (extraction: ", vn(s$extraction), "; rotation: ", vn(s$rotation), "; number of factors: ", vn(s$nFactorMethod), ").")), if (isTRUE(o$kmo) || isTRUE(o$bartlett)) tx2(" Örneklem yeterliliği KMO ölçütü ve Bartlett küresellik testi ile değerlendirilmiştir.", " Sampling adequacy was assessed with the KMO measure and Bartlett's test of sphericity.") else ""),
    pca = tx2(paste0("Temel bileşenler analizi uygulanmıştır (döndürme: ", vn(s$rotation), ")."), paste0("Principal component analysis was performed (rotation: ", vn(s$rotation), ").")),
    cfa = tx2("Ölçüm modeli doğrulayıcı faktör analizi ile sınanmış; uyum χ², CFI, TLI, RMSEA ve SRMR ile değerlendirilmiştir.", "The measurement model was tested with confirmatory factor analysis; fit was evaluated with χ², CFI, TLI, RMSEA and SRMR."),
    mancova = tx2("Birden fazla bağımlı değişken üzerindeki grup etkileri çok değişkenli varyans/kovaryans analizi (MANOVA/MANCOVA) ile incelenmiştir.", "Group effects on multiple dependent variables were examined with multivariate analysis of variance/covariance (MANOVA/MANCOVA)."),
    tx2(paste0(vn(s$title), " analizi uygulanmıştır."), paste0(vn(s$title), " analysis was performed."))
  )
}

#' Render the Method paragraph for a list of summaries
#' @export
render_method_text <- function(summaries, lang = "tr", alpha = .05, jamovi_version = NULL, r_version = NULL) {
  L <- i18n(lang)
  types <- character(); sentences <- character()
  for (s in summaries) {
    key <- s$type
    if (key %in% types) next
    types <- c(types, key)
    sentences <- c(sentences, method_sentence(s, lang))
  }
  jv <- if (is.null(jamovi_version)) "2.7" else jamovi_version
  rv <- if (is.null(r_version)) paste(R.version$major, R.version$minor, sep = ".") else r_version
  alpha_txt <- if (lang == "tr") paste0(sym("p"), " &lt; ", sub("^0", "", formatC(alpha, format = "f", digits = 2))) else paste0(sym("p"), " &lt; ", sub("^0", "", formatC(alpha, format = "f", digits = 2)))
  software <- sprintf(L$software, jv, rv, alpha_txt)
  para(paste(c(sentences, software), collapse = " "))
}
