
# This file is automatically generated, you probably don't want to edit this

reportOmvOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "reportOmvOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            run = FALSE,
            file = "",
            lang = "tr",
            secMethod = TRUE,
            secResults = TRUE,
            secList = TRUE,
            secTables = FALSE,
            alpha = 0.05,
            useLLM = TRUE,
            model = "qwen3.5:4b",
            endpoint = "http://localhost:11434",
            llmTimeout = 600, ...) {

            super$initialize(
                package="jmvReport",
                name="reportOmv",
                requiresData=FALSE,
                ...)

            private$..run <- jmvcore::OptionBool$new(
                "run",
                run,
                default=FALSE)
            private$..file <- jmvcore::OptionString$new(
                "file",
                file,
                default="")
            private$..lang <- jmvcore::OptionList$new(
                "lang",
                lang,
                options=list(
                    "tr",
                    "en"),
                default="tr")
            private$..secMethod <- jmvcore::OptionBool$new(
                "secMethod",
                secMethod,
                default=TRUE)
            private$..secResults <- jmvcore::OptionBool$new(
                "secResults",
                secResults,
                default=TRUE)
            private$..secList <- jmvcore::OptionBool$new(
                "secList",
                secList,
                default=TRUE)
            private$..secTables <- jmvcore::OptionBool$new(
                "secTables",
                secTables,
                default=FALSE)
            private$..alpha <- jmvcore::OptionNumber$new(
                "alpha",
                alpha,
                min=0.0001,
                max=0.5,
                default=0.05)
            private$..useLLM <- jmvcore::OptionBool$new(
                "useLLM",
                useLLM,
                default=TRUE)
            private$..model <- jmvcore::OptionString$new(
                "model",
                model,
                default="qwen3.5:4b")
            private$..endpoint <- jmvcore::OptionString$new(
                "endpoint",
                endpoint,
                default="http://localhost:11434")
            private$..llmTimeout <- jmvcore::OptionInteger$new(
                "llmTimeout",
                llmTimeout,
                min=30,
                max=3600,
                default=600)

            self$.addOption(private$..run)
            self$.addOption(private$..file)
            self$.addOption(private$..lang)
            self$.addOption(private$..secMethod)
            self$.addOption(private$..secResults)
            self$.addOption(private$..secList)
            self$.addOption(private$..secTables)
            self$.addOption(private$..alpha)
            self$.addOption(private$..useLLM)
            self$.addOption(private$..model)
            self$.addOption(private$..endpoint)
            self$.addOption(private$..llmTimeout)
        }),
    active = list(
        run = function() private$..run$value,
        file = function() private$..file$value,
        lang = function() private$..lang$value,
        secMethod = function() private$..secMethod$value,
        secResults = function() private$..secResults$value,
        secList = function() private$..secList$value,
        secTables = function() private$..secTables$value,
        alpha = function() private$..alpha$value,
        useLLM = function() private$..useLLM$value,
        model = function() private$..model$value,
        endpoint = function() private$..endpoint$value,
        llmTimeout = function() private$..llmTimeout$value),
    private = list(
        ..run = NA,
        ..file = NA,
        ..lang = NA,
        ..secMethod = NA,
        ..secResults = NA,
        ..secList = NA,
        ..secTables = NA,
        ..alpha = NA,
        ..useLLM = NA,
        ..model = NA,
        ..endpoint = NA,
        ..llmTimeout = NA)
)

reportOmvResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "reportOmvResults",
    inherit = jmvcore::Group,
    active = list(
        info = function() private$.items[["info"]],
        method = function() private$.items[["method"]],
        results = function() private$.items[["results"]],
        list = function() private$.items[["list"]],
        tables = function() private$.items[["tables"]],
        warnings = function() private$.items[["warnings"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Report Writer (from saved file)",
                refs=list(
                    "jmvReport",
                    "apa7"))
            self$add(jmvcore::Html$new(
                options=options,
                name="info",
                title="Info",
                visible=TRUE,
                clearWith=list(
                    "run",
                    "file",
                    "lang",
                    "useLLM",
                    "model",
                    "endpoint",
                    "alpha",
                    "llmTimeout")))
            self$add(jmvcore::Html$new(
                options=options,
                name="method",
                title="Method \u2014 Statistical Analysis",
                visible="(secMethod)",
                clearWith=list(
                    "run",
                    "file",
                    "lang",
                    "useLLM",
                    "model",
                    "endpoint",
                    "alpha",
                    "llmTimeout")))
            self$add(jmvcore::Html$new(
                options=options,
                name="results",
                title="Results",
                visible="(secResults)",
                clearWith=list(
                    "run",
                    "file",
                    "lang",
                    "useLLM",
                    "model",
                    "endpoint",
                    "alpha",
                    "llmTimeout")))
            self$add(jmvcore::Table$new(
                options=options,
                name="list",
                title="Analyses in the file",
                visible="(secList)",
                rows=0,
                clearWith=list(
                    "run",
                    "file",
                    "lang"),
                columns=list(
                    list(
                        `name`="index", 
                        `title`="#", 
                        `type`="integer"),
                    list(
                        `name`="analysis", 
                        `title`="Analysis", 
                        `type`="text"),
                    list(
                        `name`="type", 
                        `title`="jmv function", 
                        `type`="text"),
                    list(
                        `name`="variables", 
                        `title`="Variables", 
                        `type`="text"),
                    list(
                        `name`="stat", 
                        `title`="Primary statistic", 
                        `type`="text"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="es", 
                        `title`="Effect size", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="tables",
                title="Recomputed tables",
                visible="(secTables)",
                clearWith=list(
                    "run",
                    "file",
                    "lang")))
            self$add(jmvcore::Html$new(
                options=options,
                name="warnings",
                title="Warnings",
                visible=TRUE,
                clearWith=list(
                    "run",
                    "file",
                    "lang",
                    "useLLM",
                    "model",
                    "endpoint")))}))

reportOmvBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "reportOmvBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jmvReport",
                name = "reportOmv",
                version = c(1,0,0),
                options = options,
                results = reportOmvResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'na')
        }))

#' Report Writer (from saved file)
#'
#' Reads every analysis stored in a saved jamovi file (.omv), recomputes the 
#' results and writes APA-style Method and Results text. Numbers always come 
#' from the computed results. An optional local language model (Ollama) only 
#' rewords the text; the output is verified against the computed numbers.
#' 
#'
#' @examples
#' reportOmv(file = "", lang = "tr", run = TRUE)
#'
#' @param run tick to (re)generate the report; keeps jamovi responsive while
#'   setting options
#' @param file path to a saved jamovi file; empty means auto-detect the newest
#'   .omv in Documents/Desktop/Downloads
#' @param lang .
#' @param secMethod .
#' @param secResults .
#' @param secList .
#' @param secTables .
#' @param alpha .
#' @param useLLM .
#' @param model .
#' @param endpoint .
#' @param llmTimeout .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$info} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$method} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$results} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$list} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$tables} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$warnings} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$list$asDF}
#'
#' \code{as.data.frame(results$list)}
#'
#' @export
reportOmv <- function(
    run = FALSE,
    file = "",
    lang = "tr",
    secMethod = TRUE,
    secResults = TRUE,
    secList = TRUE,
    secTables = FALSE,
    alpha = 0.05,
    useLLM = TRUE,
    model = "qwen3.5:4b",
    endpoint = "http://localhost:11434",
    llmTimeout = 600) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("reportOmv requires jmvcore to be installed (restart may be required)")


    options <- reportOmvOptions$new(
        run = run,
        file = file,
        lang = lang,
        secMethod = secMethod,
        secResults = secResults,
        secList = secList,
        secTables = secTables,
        alpha = alpha,
        useLLM = useLLM,
        model = model,
        endpoint = endpoint,
        llmTimeout = llmTimeout)

    analysis <- reportOmvClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

